interface User {
  id: number,
  full_name: string,
  email: string,
  phone_number: string,
  google_id: string,
  password: string,
  birth_date: Date,
  gender: "Laki-Laki" | "Perempuan",
  phone_number_verified_at: Date,
  avatar: string,
  role: "Admin" | "Staff" | "Customer",
  remember_token: string,
  status_account: "Active" | "Inactive" | "Pending",
  last_login_date: Date,
  reason_delete: string,
  created_at: string,
  updated_at: string,
  deleted_at: string
}